### PR TITLE
Change license to "MIT License" to align with team open source license policy

### PR DESCRIPTION
**Pull request by LiweiPeng**

### CODE REVIEW

**Comment by LiweiPeng** [comment]
For this change, 1) Anand recommends me to use "MIT License" instead of Apache License; 2) Because our long term plan is to use fluentd plugin in LAD and LAD is using "MIT license", it is good to keep them consistent.

**Comment by hosungsmsft** [comment]
What I'm saying is I still don't think 'because LAD uses "MIT License"' is an appropriate title for this change. I'd say you may use something like 'to align with our team's open source licensing policy'.

**Comment by LiweiPeng** [comment]
Thanks. That makes sense. I updated the title.

**Comment by LiweiPeng** [comment]
make sense. I'll discard this one. I created a new one. https://github.com/Azure/fluentd-plugin-mdsd/pull/10

**Pull request closed without merging**
